spring:
  application:
    name: manual
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/testdb}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: ${PORT:8081}

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %class.%M [rid=%X{rid}] - %msg%n"

app:
  guest-login:
    login-id: ${GUEST_LOGIN_ID:}
    password: ${GUEST_LOGIN_PASSWORD:}
