# application-prod.yml
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
